Remove deprecated class ArrayCollection
OpenConext/Stepup-Gateway pull request #203
Opened 2020-11-19 11:09 UTC by mroest

In preparation for a SF4 upgrade this removes the deprecated ArrayCollection
class.

2020-11-19 13:34 UTC, MKodde requested changes
The change looks good. Some suggestions:

1. Add type definitions, now that we are no longer supporting PHP 5.4, this is a good way to make the code more reliable.
2. Consider adding a simple unit test to verify the correct working of this repo.

Other than that, nice to see the removal of the dependency on the array collection!

2020-11-20 10:36 UTC, thijskh commented on src/Surfnet/StepupGateway/SamlStepupProviderBundle/Provider/ProviderRepository.php
> +     * @var []]Provider
typo here?

2020-11-23 07:53 UTC, MKodde approved these changes
Except for the typo, LGTM. Thanks for adding the test!

2020-11-23 07:53 UTC, MKodde commented on src/Surfnet/StepupGateway/SamlStepupProviderBundle/Tests/Provider/ProviderRepositoryTest.php
> +class ProviderRepositoryTest extends TestCase
:muscle:

2020-11-24 09:04 UTC, mroest commented on src/Surfnet/StepupGateway/SamlStepupProviderBundle/Provider/ProviderRepository.php
> +     * @var []]Provider
Thanks! Good Catch! Fixed

2020-11-24 09:09 UTC, merged